# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0356b5a881806bad494d7f050abe79fb4638c4a02751ef9871423b5913e49680ff4e60eebe37da5484266385973f61dfa6b7ae286d55595dca2efada935798ed

test:
  secret_key_base: 6e6be5a51d01280ca193ad68073cef062ce8f1fb77b8131ece6bc9deb95be33eed0f2ce6b31d0094dbddcb80c4e58f9439de1be900ad4569412da38b5d59a759

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
staging:
  secret_key_base: 
